import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Concepts',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'concepts/architecture',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
      },
      items: [
        'api/http-api',
        {
          type: 'category',
          label: 'SDK Reference',
          link: {
            type: 'generated-index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/sdk'
            }
          ]
        }
      ],
    },
  ],
};

export default sidebars;
